apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-namespaces
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/SEU_USUARIO/openshift-ai-lab-gitops.git'
    targetRevision: main
    path: namespaces
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
