apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - openshift-nfd.yaml
  - nvidia-gpu-operator.yaml
  - redhat-ods-operator.yaml
  - redhat-ods-applications.yaml
  - redhat-ods-monitoring.yaml
  - rhods-notebooks.yaml
  - ai-gpu-lab.yaml
