apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhods-operator
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/alcarv/openshift-ai-lab-gitops.git'
    targetRevision: main
    path: operators/rhods-operator
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redhat-ods-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
