apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhods-instance
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: 'https://github.com/alcarv/openshift-ai-lab-gitops.git'
    targetRevision: main
    path: instances/rhods
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redhat-ods-applications
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 30s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
